<?xml version = "1.0"?>
<robot name = "wheel" xmlns:xacro = "http://ros.org/wiki/xacro">

  <xacro:property name = "PI"       value = "3.1415926535897931"/>
  <xacro:property name = "wheel_r"  value = "0.024"/>
  <xacro:property name = "wheel_h"  value = "0.008"/>
  <xacro:property name = "wheel_m"  value = "0.112"/>

  <xacro:macro name = "wheel" params = "rl parent">
    <!-- wheels -->
    <link name = "wheel_${rl}">
      <visual>
        <geometry>
          <cylinder length = "${wheel_h}" radius = "${wheel_r}"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <cylinder radius = "${wheel_r}" length = "${wheel_h}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz = "0 0 0" rpy = "0 0 0"/>
        <mass value = "${wheel_m}" />
        <inertia  ixx = "${wheel_m*(3*wheel_r*wheel_r+wheel_h*wheel_h)/12}" ixy = "0"  ixz = "0"
                  iyx = "0"  iyy = "${wheel_m*(3*wheel_r*wheel_r+wheel_h*wheel_h)/12}" iyz = "0"
                  izx = "0"  izy = "0"  izz = "${wheel_m*(wheel_r*wheel_r)/2}"/>
      </inertial>
    </link>

    <joint name = "wheel_${rl}_joint" type = "continuous">
      <parent link = "${parent}"/>
      <child link = "wheel_${rl}"/>
      <xacro:if value = "${rl == 'r'}">
        <origin xyz = "0.04 0 ${0.022 - 0.0275}" rpy = "0 ${PI/2} 0"/>
      </xacro:if>

      <xacro:if value = "${rl == 'l'}">
        <origin xyz = "-0.04 0 ${0.022 - 0.0275}" rpy = "0 ${PI/2} 0"/>
      </xacro:if>

      <axis xyz = "0 0 -1"/>
      <limit effort = "10" velocity = "10"/>
      <joint_properties damping = "0.0" friction = "0.0"/>
    </joint>

  </xacro:macro>

</robot>